# Generated by Django 5.0.6 on 2024-07-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(upload_to='media/upload/cover'),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.FileField(upload_to='media/upload/music'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='cover',
            field=models.ImageField(upload_to='media/upload/cover'),
        ),
    ]
