# Generated by Django 5.0.6 on 2024-07-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_alter_article_cover_alter_music_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='title',
            field=models.CharField(default='TEST', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poem',
            name='title',
            field=models.CharField(default='TEST', max_length=200),
            preserve_default=False,
        ),
    ]
