# Generated by Django 5.0.6 on 2024-07-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0004_music_title_poem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date updated'),
        ),
    ]
