# Generated by Django 5.0.6 on 2024-07-21 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0005_alter_music_update_date_alter_poem_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='music',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
        ),
    ]
