# Generated by Django 5.0.6 on 2024-07-21 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0006_alter_article_update_date_alter_music_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='music',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='poem',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='poem',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
