# Generated by Django 5.0.6 on 2024-07-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0008_alter_article_pub_date_alter_article_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='composer',
            field=models.CharField(default='Redemption Singers', max_length=50),
            preserve_default=False,
        ),
    ]
